### ISSUE TITLE
Arabic 508, Overview and Primary Texts

### ISSUE THREAD

**Issue by wlpotter** [UCLALibrary/sinai_metadata#14]
https://sinaimanuscripts.library.ucla.edu/catalog/ark:%2F21198%2Fz1db957p

- [x] Outline created
- [x] Textual contents described

**Comment by ChrisPrejean** [comment]
@kirschbombe @wlpotter  : Sinai AR 508 overview attached. I left details in, but I already did a lot of spade work on this one.

[Metadata gathering iteration 2 AR 508.docx](https://github.com/UCLALibrary/sinai_metadata/files/9250421/Metadata.gathering.iteration.2.AR.508.docx)

**Comment by wlpotter** [comment]
Hi @ChrisPrejean this looks great! I think this one is really interesting for thinking about which are the 'Texts' in the manuscript and which are the 'sub-sections' of the text. You have, for instance, some clear divisions using decorative borders, though you get different motifs (e.g., f. 9r, 142v, etc. vs 38v vs 144v), but you also seem to have texts introduced with the rubricated basmalah and no border. And then you have texts with an unrubricated basmalah (e.g., the introduction to Palladius on 36r). In any case, I think this will be a good question to keep in mind as you start deciding which are the primary textual divisions and which are the sub-sections. In this vein, I think your observation about the thematic focus on Sinai is intriguing!

One specific question, here, would be to think about whether ff. 1-8 are functioning as fly-leaves, in which case that text might be a 'secondary text' rather than a 'primary text' (similar to the text on f. 159r); or perhaps we are missing the beginning portion of it and it should be considered the first textual item in the manuscript?

I agree that ff. 80-84 are parchment, and it seems to me that they are the only leaves that are (though we can take a closer look when you get to the codicological analysis part).

One small note, I think there was a typo for the start of the Apophthegmata which should be 76v rather than 77r, where you have the decorative border?

Finally, good catch on the duplicate label of 158v! I think the images are just mislabelled as the folio looks to be numbered 159. We will update the image labels.

**Comment by ChrisPrejean** [comment]
Thanks @wlpotter. Lots of useful tips and insight that will help me move forward. I especially like your mention of the rubrications and division of primary/secondary texts. Thanks! 


> One small note, I think there was a typo for the start of the Apophthegmata which should be 76v rather than 77r, where you have the decorative border?

 You are correct, and I have made the correction and added it to the attached document.


[Metadata gathering iteration 2 AR 508.docx](https://github.com/UCLALibrary/sinai_metadata/files/9256581/Metadata.gathering.iteration.2.AR.508.docx)

**Comment by ChrisPrejean** [comment]
@wlpotter @kirschbombe : here is the overview of Arabic 508. Added to airtable. I did not take any notes on secondary and paratexts. I also uploaded it to the google drive folder unconverted from a Microsft word file (whoops!)

[Arabic 508.docx](https://github.com/UCLALibrary/sinai_metadata/files/9810098/Arabic.508.docx)

**Comment by wlpotter** [comment]
@ChrisPrejean looks great! No worries about adding it as a word file; I converted it to a Google Doc: https://docs.google.com/document/d/1oB-QPWrT4naElqtabPJOaK4VO1L9H2ijoGVFrDuPAuA/edit (just fyi if you open it from google drive and go to the `file` menu you get an option to 'save as Google doc', which is what I did with the others)
