### ISSUE TITLE
Sinai Arabic 580, Overview and Primary Texts

### ISSUE THREAD

**Issue by wlpotter** [UCLALibrary/sinai_metadata#22]
https://sinaimanuscripts.library.ucla.edu/catalog/ark:%2F21198%2Fz1rb8t1k

- [x] Outline created
- [x] Textual contents described

**Comment by kirschbombe** [comment]
Thank you, @ChrisPrejean. I did a quick read and this looks really great. Both @wlpotter and I are out of the office today, so we'll take a closer look early next week.

**Comment by wlpotter** [comment]
Hi @ChrisPrejean; this is great! I think you’re good to move onto the text description phase for this ms. I have made a few changes to [the Google doc](https://docs.google.com/document/d/12ExJVZRyvxUqoxhrOYltkzOTKiRqnRbM8wNPK0Ue8SI/edit), so make sure to grab the Text Description and Codicological Analysis sections from there so it’s up to date.

One other thought, as you start on the text description. My understanding is that Arabic manuscripts in the Islamic tradition often have all sorts of preliminary material before getting to the start of the 'text proper' -- prefaces, statements of authorship, dedications, content lists, etc. I'm not sure how often this happens in Christian Arabic manuscripts, and I also don't know how often these kinds of preliminary materials are the work of individual copyists or are/become part of the tranmission history of the text. Still, I'm curious, @ChrisPrejean, if this manuscript contains any of this material or if it jumps straight into the 'text'? Also, @kirschbombe I wonder if we should treat these kinds of preliminaries as paratexts, if they are crucial to record at all, or if we treat them some other way.

@kirschbombe I wanted to flag a few other bits of data that don’t perfectly fit into the current model.

1. Information about rubrication that is not the title of a work or its sub-sections. This also occurs in some liturgical texts. Would this go in a contents note? An example from this ms: 
>Division of the Earth is rubricated by the Arabic letter, ه, f. 53r-54r...

Here the sub-section's title(s) are not rubricated, but rubrication is still used for a similar function.

2. Filiation notes. As Chris notes, 
>There is a partial copy of the same History in Sinai AR 456, 103r-164v.

Do we include this kind of information? Eventually we would be able to tell that these links exist based on shared work authority records. A similar case might be where we know that one ms was the exemplar for another -- this could either be a note, to begin with, or eventually part of the object relationship schema.

**Comment by wlpotter** [comment]
Sorry @ChrisPrejean just to clarify. Go ahead and do the outlining for the other two mss first, and then you can start working on the text description phase for all three.

**Comment by kirschbombe** [comment]
Hi, @ChrisPrejean and @wlpotter. For the question about front matter/paratexts, I think we'll try to note as much as we can for now, then decide (based on what we have in our manuscripts) the best approach. For now, let's just note any front matter or paratextual material so we know it's there and its general nature.

For rubrication, I'm not sure if content note is the right choice (although it might be the best choice for now). Let's just keep it as a more general note until we decided which note it fits into or if we need a new note type. 

In the case of filiation, we definitely want to record that info if we know, so we would need to add our justification for saying that something is copied from or the original. In general though, work authorities will link these two records together.

**Comment by ChrisPrejean** [comment]
@wlpotter @kirschbombe: 

> Still, I'm curious, @ChrisPrejean, if this manuscript contains any of this material or if it jumps straight into the 'text'?

In this ms there is an opening basmala: In the name of God, the Most Compassionate, the Most Merciful (in other texts, there is the basmala In the Name of the Father, Son, and Holy Spirit). Other than that, there is a title, then the text. In the preliminary materials, there is a waqf or multiple  waqf statement(s) and a warning that anyone who should remove or take the [book] away from the monastery shall be anathematized (these also occur at the material at the end). This is common to the Sinai mss. There is sometimes multiple waqf statements by bishops or monks from different periods. For example in AR 580 there is one from the Archbishop Theodosius (circa 1440) on 1v, one from an Archbishop John (circa 1264 or 1265) on 3r, and one more in between on folio 2r (though I cannot yet read the name yet).  It should be noted that the waqfiyya statements made by these men appear on many manuscripts, which Alexander (Sasha) Treiger points out; John and Theodosius appear frequently: (https://www.academia.edu/43359869/SINAITICA_2_Ioasaph_of_Rhodes_Inventory_of_the_Archbishops_of_Sinai)

**Comment by ChrisPrejean** [comment]
@kirschbombe @wlpotter : AR 580 description of primary, secondary, and paratexts. 

[Metadata gathering2-580.docx](https://github.com/UCLALibrary/sinai_metadata/files/9762863/Metadata.gathering2-580.docx)

**Comment by wlpotter** [comment]
@ChrisPrejean Thanks for this! I also saw that you added the primary text info to the Airtable form. I think this document will be good to hang on to for when we work on adding paratexts and secondary texts.

For now let's call this one 'done' and we'll circle back to it for the paratextual and codicological information after we've got a bit more data from other manuscripts. Does that sound right @kirschbombe ?

**Comment by kirschbombe** [comment]
Yes, that sounds great. Although we might want to flag it somehow for the paratextual content so it's easy to find all the ones we need to loop back to. Or we can start a separate list for mss with paratexts somewhere in Google drive and link to this issue?

**Comment by wlpotter** [comment]
FYI I have converted the word doc to a Google Doc: https://docs.google.com/document/d/1NpSq7fP9ncQTOvnJKhXTB9PXdiDBPSVhBVXyaCsiX4E and added it to the "Metadata" folder in the RA work folder.

I've also started a Google sheet to better track which mss we need to come back to for paratexts, etc.: https://docs.google.com/spreadsheets/d/1juo2DJxn_ZR93aErVXDcJzbm25Gzmpg1xwvHHoz3bLk

**Comment by wlpotter** [comment]
Additional work on this split into #55 and #56. Marking this issue as 'done'
