### ISSUE TITLE
Sinai Arabic 320, Overview and Primary Texts

### ISSUE THREAD

**Issue by wlpotter** [UCLALibrary/sinai_metadata#23]
https://sinaimanuscripts.library.ucla.edu/catalog/ark:%2F21198%2Fz18s67k3

- [x] Outline created
- [x] Textual contents described

**Comment by ChrisPrejean** [comment]
@kirschbombe @wlpotter : introductory remarks on AR 32
[Metadata gathering2-AR320.docx](https://github.com/UCLALibrary/sinai_metadata/files/9190179/Metadata.gathering2-AR320.docx)
0

**Comment by wlpotter** [comment]
Hi @ChrisPrejean this looks great! I think it's ready for more detailed text description, once you've got the outline done for the last ms.

There seem to be a lot of really interesting paratexts in this one, with several having associated dates. I'll be interested to hear what you find out about how they relate to the texts and to the manuscript's history as a whole.

There's also some really fascinating codicological things going on, too, with the use of parchment on both ends as fly-leaves(?). And the use of foliation marks only on the first text. This will be a fun one to discuss when you get to the codicological analysis phase!

Three quick, minor things to flag:
- Remember to include "Arabic" in the shelfmark, as there could be a Syriac 320; Greek 320, etc.
- One section of the text description is for decorations. Youc an go ahead and include the cross on f. 126v there. I'm not sure about the four dots&mdash;could you send a folio number? It is possible they are just common editorial markings rather than ornamentation.
- You asked if we need to track down foliation for the other Sinai mss that have the first text. @kirschbombe let me know what you think, but I'm inclined to say just noting which shelfmarks is sufficient for now?

**Comment by kirschbombe** [comment]
For the related Sinai mss, I think the shelfmark is fine for now, but if the foliation is easy to find/handy, then go ahead and include it :)

**Comment by ChrisPrejean** [comment]
@kirschbombe @wlpotter : here is AR320 description of primary, secondary, and paratexts (brief). The codicological analysis is not complete. 
[Metadata gathering2-AR320.docx](https://github.com/UCLALibrary/sinai_metadata/files/9762841/Metadata.gathering2-AR320.docx)

**Comment by wlpotter** [comment]
@ChrisPrejean this is great! It also looks like the primary texts have been added to the Airtable form. We should keep this document, as with #22, for when we get to paratexts, etc.

I noticed that you left a few comments in the margins of the Word doc. Do you want to review this one together before marking it 'done' for phase 1?

**Comment by wlpotter** [comment]
FYI I converted the word doc into a Google Doc: https://docs.google.com/document/d/1_IBNpnSxKruqI7VZqbz4BGJIlKUz8VRFmKBzO8C4_Cc

I will be putting these in our main Google Drive folder under "Metadata"

**Comment by wlpotter** [comment]
Additional work split off into #53 and #54. Marking this phase as 'done'.
