### ISSUE TITLE
Revise Textual Artifact JSON Sample Records

### ISSUE THREAD

**Issue by wlpotter** [UCLALibrary/sinai_metadata#31]
This issue gathers together lingering questions and notes for discussing additional revisions for the textual artifact JSON sample. The version of this file referenced below is: https://github.com/UCLALibrary/sinai_metadata/blob/c6061134d40e5cd8dc39eadaaa82c163fe93575a/data-model/SDP-sample-records/textual-artifact_sample1.json

# Notes and Questions

1. [line 16](https://github.com/UCLALibrary/sinai_metadata/blob/c6061134d40e5cd8dc39eadaaa82c163fe93575a/data-model/SDP-sample-records/textual-artifact_sample1.json#L16): **Notes on the use of TOC** I think the items in ‘toc’ can be as simple as title and locus, or even just title. But they can also be much more elaborate. I don't think we give them an id though? It's also possible we use the toc field for more simple lists of titles and have a separate field, like 'items', or 'parts', or 'contained_texts’, for the more structured contents list that links to work authorities and has associated paratexts, etc.? This is a much larger question for which I will make a separate issue
2. [line 19](https://github.com/UCLALibrary/sinai_metadata/blob/c6061134d40e5cd8dc39eadaaa82c163fe93575a/data-model/SDP-sample-records/textual-artifact_sample1.json#L19): **Locus for TOC item**. as with decorations and paratexts, locus seems more appropriate here than range (compare use of range in page_layout)
3. [line 22](https://github.com/UCLALibrary/sinai_metadata/blob/c6061134d40e5cd8dc39eadaaa82c163fe93575a/data-model/SDP-sample-records/textual-artifact_sample1.json#L22): **Incomplete sample**. I think these probably all had paratexts, like rubrics or final rubrics. But I didn’t add them in here…
4. [lines 46-82](https://github.com/UCLALibrary/sinai_metadata/blob/c6061134d40e5cd8dc39eadaaa82c163fe93575a/data-model/SDP-sample-records/textual-artifact_sample1.json#L46-L82): **Paratexts in TOC Items**. I recommend allowing, but by no means requiring, a full-fledged paratext description if it corresponds only to a sub-item. Another use case for this expansive TOC would be a thematic collection of hagiography where we would want to specify the individual vitae, which might have rubrics and associated/commemorated persons.
5. [line 86](https://github.com/UCLALibrary/sinai_metadata/blob/c6061134d40e5cd8dc39eadaaa82c163fe93575a/data-model/SDP-sample-records/textual-artifact_sample1.json#L86): **Textual Artifact level events?** not sure that we would ever have text-specific events?
6. [line 87](https://github.com/UCLALibrary/sinai_metadata/blob/c6061134d40e5cd8dc39eadaaa82c163fe93575a/data-model/SDP-sample-records/textual-artifact_sample1.json#L87): **Example-specific use of paratexts at content level rather than artifact level**. because the paratexts in this example are for specific sub-items, i.e. the Gospel of John's final rubric, I am putting them there. If we had a rubric that said 'The Gospels, which we've written by divine aid' or something like that, we could put that in the main paratexts field.
7. [line 88-90](https://github.com/UCLALibrary/sinai_metadata/blob/c6061134d40e5cd8dc39eadaaa82c163fe93575a/data-model/SDP-sample-records/textual-artifact_sample1.json#L88-L90): **General associated data in Texts** including these fields in case we have indirect evidence for entities at the artifact level (i.e., they are not attested in paratexts, or in contents' paratexts)
8. [line 90](https://github.com/UCLALibrary/sinai_metadata/blob/c6061134d40e5cd8dc39eadaaa82c163fe93575a/data-model/SDP-sample-records/textual-artifact_sample1.json#L90): **Decorations in texts**. should we include decorations field at the textual artifact level? For, e.g., illustrations of a pericope? Would a headpiece be included at the textual artifact level since it's for the title of the text?

## A Note on Contents Data

This corresponds to [lines 13-85](https://github.com/UCLALibrary/sinai_metadata/blob/c6061134d40e5cd8dc39eadaaa82c163fe93575a/data-model/SDP-sample-records/textual-artifact_sample1.json#L13-L85). We likely want to spin this off into its own issue to document our discussion and decisions. The lines in this commit are the results of our discussion about what is and is not a textual artifact, and are an attempt to adhere to that distinction while allowing us to capture some of the granular data about sub-parts of a textual artifact. Here are a few further notes on the subject:

I think we do want multiple, more or less structured, ways to define the sub-items within a textual artifact. I agree that we should define an artifact based on what we can tell of the intention of the producers of the ms (i.e., which texts or groups of texts are represented in the ms as a cohesive unit?). And that artifacts shouldn’t ‘nest’, even if they contain semi-distinct intellectual contents as in the case of the Gospels, or a liturgical service made up of different prayers and hymns. The artifact is the Gospels, even if we want to include information about where the individual books start and end.

A contents note may provide general, unstructured information about the sub-items. We could use 'toc' for a bit more structured data (like a list of titles and even locus ranges). We could also use the ‘toc’ field, as I've done here, to provide structured information about the sub-items contained within an artifact. For instance, we could gather information about which hymns, sermons, etc. make up a liturgical service. These could be linked to work records, as a user might be interested either in the service as a whole or the witnesses for a particular hymn that features in it. Each item in the TOC could also contain paratextual information like rubrics, etc. that could link to attested authors, etc. It is possible we want to have a dedicated field for this kind of structured data and leave TOC to be more prose-y.

The items in the ‘toc’ field could have most of the same fields as a textual artifact, such as associated persons, extent, paratexts, etc. (This would be useful for providing attested information, name variants, etc. for person and work records). But we wouldn’t make them full-on textual artifact records, and they wouldn't get their own IDs -- I'm also not sure if they're associated paratexts should get IDs or not. One potential complication might be parts of an artifact that themselves have sub-parts (a liturgical book with services for the whole year comes to mind -- each service would be an item in the 'toc' but would consist of sub-items for the parts of the service, etc.). Allowing a TOC item to have its own TOC opens up the kind of infinite nesting that we didn't like about nesting textual artifacts. Maybe this is less of an issue since we aren't giving them IDs, or maybe we don't allow hierarchical TOCs?

I think another benefit of having ‘contents’ with various fields within it allows us to capture different levels of detail, depending on how much time, interest, or expertise is available to a given textual artifact.

**Comment by kirschbombe** [comment]
For #2 - I was just looking at the first sample record and thought the same when I saw that it was a range instead of an extent statement. +1 for using `locus`

**Comment by kirschbombe** [comment]
For # 4 - I think I agree with your comment, but this might be one of the enhancements that we add in a subsequent phase if we have a sufficient number of examples to work with.

**Comment by wlpotter** [comment]
For # 5, if we decide to include events sourced to paratextual evidence, we could potentially have a use/read-by event that is sourced to a reader's note.

**Comment by wlpotter** [comment]
Deprecated by #49
