### ISSUE TITLE
General Authority File Field list for SDP Authority Files

### ISSUE THREAD

**Issue by wlpotter** [UCLALibrary/sinai_metadata#37]
Below is a list, subject to revision, of the fields available for any of the authority file types in the Sinai Data Portal (person, place, work, writing system, script). Each entity type has additional fields available to it. Note that these only include fields we would define directly in each authority file and does not include the fields that may be computed based on other data links _to_ the authority files (see, e.g., item 9 "Associated Objects" in #35)

# Fields

- id
- label
- entity_type
- type(s)
- uniform_name
- descriptions
- authority_files
- associated_dates
- associated_entities
- notes
    - general notes, perhaps with different typologies? I think leaving these as is should be fine for now.
- references
- contributor

----

# Notes

- type(s)
  - I am wondering if `role` is a better field name to distinguish between, e.g., the kind of place (settlement, country, mountain) and the nature of the place's relationship to a given object (place-of-production, etc.). This field may also not be useful for all entity types; I'm not sure, for instance, how applicable it is to writing system and script.
  - The CVs would differ for this field for each entity type, of course, even if the field key is the same.
  - We may need to define a `primary_type` or `primary_role` for entities that may have multiple functions within our data (e.g., a scribe who added an original composition to a manuscript is both "scribe" and "author", but is primarily a "scribe).
- authority_files
  - The way I've currently structured the JSON does not allow for non-URI identified authority files, but we would want to model this so that we can have data from things like CPG, BHO, and other standard, non-digitized reference sources.
- associated_dates
  - The date types available would differ by entity type (so only persons can have 'birth-date', for instance). 
  - Dates may change to events to match how we're currently thinking about modeling the associated events in object types.
- associated_entities
  - Do these need to be more specific? Do we need separate fields for each entity? Do we need to specify the nature of the association (this would help with LOD serialization I think)?
- notes
  - perhaps include different typologies of notes? (incerta, disambiguation, etc.) This may be a future enhancement.

After revision of this list, the final set of fields should be added to project documentation.

**Comment by kirschbombe** [comment]
I think for person roles it might be better to have the roles assigned in the context of the codicological unit and not directly to an authority. So, the roles would accumulate as that name is associated with new objects or units and we don't need to assert a primary role.

**Comment by wlpotter** [comment]
Deprecated by #49
